package dmescher.soapyhearts.common;

public enum GameOpCodeStatus {
	SUCCESS, BAD_GAMEID, BAD_TOKEN, BAD_PLAYER, INVALID_STATE, BAD_PASS, BAD_LEAD_2C, BAD_LEAD_H,
	BAD_CARD_POINTS, BAD_CARD_SUIT, NOT_YOUR_TURN, NOT_YOUR_CARD, BAD_TRICK, BLANK_CARD, INVALID_CARD
}
